# Generated by Django 2.1.3 on 2018-12-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('carnum', models.CharField(max_length=6)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cartype', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
