# Generated by Django 2.1.3 on 2018-12-13 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caruser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='caruser',
            name='carnum',
        ),
        migrations.RemoveField(
            model_name='caruser',
            name='cartype',
        ),
        migrations.RemoveField(
            model_name='caruser',
            name='date',
        ),
        migrations.RemoveField(
            model_name='caruser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='caruser',
            name='phone',
        ),
    ]
