# Generated by Django 2.1.3 on 2018-12-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181213_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnum', models.CharField(max_length=50)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('car_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'car'), (2, 'van'), (3, 'pick-uptruck')], null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CarUser',
        ),
    ]
