# Generated by Django 2.1.3 on 2018-12-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20181221_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='carnum',
            new_name='carnumber',
        ),
    ]
